export const GET_EMPLOYMENTS = "GET_EMPLOYMENTS";
export const GET_EMPLOYMENT = "GET_EMPLOYMENT";
export const CREATE_EMPLOYMENT = "CREATE_EMPLOYMENT";
export const EDIT_EMPLOYMENT = "EDIT_EMPLOYMENT";
export const DELETE_EMPLOYMENT = "DELETE_EMPLOYMENT";
